---
title: "SNA"
author: "katya"
date: '2022-05-27'
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(readr)
```

```{r cars}
data = read_csv("~/R/clean_data.csv")
```

```{r pressure, echo=FALSE}
library(igraph)
library(ggraph)
library(network)
library(sna)
library(visNetwork)
library(threejs)
library(networkD3)
library(ndtv)
library(qgraph)
library(splitstackshape)
library(tm)
```

```{r}
count_bigrams <- function(dataset) {

  dataset %>%

    unnest_tokens(bigram, clean, token = "ngrams", n = 2) %>%

    separate(bigram, c("word1", "word2"), sep = " ") %>%

    filter(!word1 %in% stop_words$word,

           !word2 %in% stop_words$word) %>%

    count(word1, word2, sort = TRUE)
}
```



```{r}
visualize_bigrams <- function(bigrams) {

  set.seed(2016)

  a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

  

   bigrams %>%

    graph_from_data_frame() %>%

    ggraph(layout = "fr") +

    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a) +
 geom_node_point(color = "lightblue", size = 5) +

    geom_node_text(aes(label = name), vjust = 1, hjust = 1) +

    theme_void()

  

}

```


```{r}

visualize_bigrams_individual <- function(bigrams) {

  set.seed(2016)
   a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

  

  net = bigrams %>%

    graph_from_data_frame() %>%

    ggraph(layout = "fr") +

    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a,end_cap = circle(.07, 'inches')) +

    geom_node_point(color = "lightblue", size = 5) +

    geom_node_text(aes(label = name), vjust = 1, hjust = 1) +

    theme_void()
}


```

```{r}

Words <- clean_data %>%

  count_bigrams()

```

```{r}
Words %>%

  filter(n > 10) %>%

  visualize_bigrams()
```
